### ISSUE TITLE
Update your GitHub homepage to point to the package

### ISSUE THREAD

**Issue by kevmoo** [ForceUniverse/cargo#6]
https://pub.dartlang.org/packages/cargo

Makes it really easy to see what the latest published version is

**Comment by jorishermans** [comment]
Done, added on the homepage ...

**Comment by kevmoo** [comment]
To be clear: I was referring to the GitHub page – you can click 'edit' at the root and add a URL

**Comment by jorishermans** [comment]
Okay, that is indeed better!

**Comment by kevmoo** [comment]
There ya go!
