### ISSUE TITLE
Indexedbd support

### ISSUE THREAD

**Issue by Hecatoncheir** [ForceUniverse/cargo#7]
Hey. Thank you for a good package! Is indexeddb already supported?

**Comment by jorishermans** [comment]
Yes it is.

This is the implementation of indexeddb in Cargo.

https://github.com/ForceUniverse/cargo/blob/master/lib/src/client/indexdb_impl.dart

Only the sync methods are not supported, because indexeddb is by nature asynchronous.

Can you take a look if this implementation is good for you?

**Comment by Hecatoncheir** [comment]
Yes, that's what I need. Thanks!

**Comment by jorishermans** [comment]
Great! Let me know if you are missing some functionality that would be great in this package.
